### ISSUE TITLE
New feature request: display user test summary

### ISSUE THREAD

**Issue by alv2017** [mary-bykouskaya/Multiplication_for_Kids#1]
Display 10 question summary. In the summary you need to display each question from the test. For every question you need to display:

    - question number
    - question
    - student's answer
    - correct answer
    - answer status (CORRECT or WRONG)

Example:

*** SUMMARY ***

Q1: 2 x 3 = ?; Student Answer: 6; Answer: 6; Status: CORRECT
Q2: 6 x 8 = ?; Student Answer: 56; Answer: 48; Status: WRONG

Kind Regards,
Vitalija

**Comment by mary-bykouskaya** [comment]
Completed
